name: asset_gen
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - protobuf
  - tokenizers
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4
  - diffusers==0.30.0
  - transformers==4.41.2
  - huggingface_hub==0.33.1
  - xformers==0.0.25
  - pip:
      - sentencepiece
      - accelerate
      - charset_normalizer
      - chardet
