name: asset_gen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.14
  - pip
  - numpy
  - pillow
  - protobuf
  - tokenizers==0.15.2
  - diffusers==0.34.0
  - transformers==4.38.2
  - huggingface_hub==0.33.1
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - --index-url https://download.pytorch.org/whl/cu124
      - bitsandbytes==0.42.0
      - sentencepiece
      - accelerate==1.7.0
      - charset_normalizer
      - chardet
      - xformers==0.0.27.post2
      - flash-attn==2.8.0.post2